Загрузите в колаб файлы по оценкам (ratings) и фильмам (movies) и создайте на их основе pandas-датафреймы

In [ ]:
import pandas as pd

In [ ]:
df_ratings=pd.read_csv("u.data.csv",sep='\t',names=["user id","item id","rating","timestamp"])

In [ ]:
df_movies=pd.read_csv("u.item.csv",sep='|',encoding='ISO-8859-1',names=["movie id","movie title","release date","video release date","IMDb URL","unknown","Action"," Adventure","Animation","Children's","Comedy","Crime","Documentary","Drama","Fantasy","Film-Noir","Horror","Musical","Mystery","Romance","Sci-Fi","Thriller","War","Western"])

In [ ]:
df_ratings

       user id  item id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [ ]:
df_movies.head()

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

Средствами Pandas, используя dataframe ratings, найдите id пользователя, поставившего больше всего оценок

In [ ]:
df_ratings['user id'].value_counts()

405    737
655    685
13     636
450    540
276    518
      ...
441     20
36      20
812     20
895     20
93      20
Name: user id, Length: 943, dtype: int64

Оставьте в датафрейме ratings только те фильмы, который оценил данный пользователь

In [ ]:
df_r = df_ratings[ df_ratings['user id']==405  ]
df_r.head()

       user id  item id  rating  timestamp
12276      405       56       4  885544911
12383      405      592       1  885548670
12430      405     1582       1  885548670
12449      405      171       1  885549544
12460      405      580       1  885547447

**Добавьте к датафрейму из задания 3 столбцы:**

●	**По жанрам. Каждый столбец - это жанр. Единицу записываем, если фильм ** **принадлежит данному жанру и 0 - если нет **

●	**столбцы с общим количеством оценок от всех пользователей на фильм и суммарной**
 **оценкой от всех пользователей **

In [ ]:
df_r.rename(columns={'item id': 'movie id'}, inplace=True)
df_r.head(5)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

       user id  movie id  rating  timestamp
12276      405        56       4  885544911
12383      405       592       1  885548670
12430      405      1582       1  885548670
12449      405       171       1  885549544
12460      405       580       1  885547447

In [ ]:
df_r.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 737 entries, 12276 to 99756
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user id    737 non-null    int64
 1   movie id   737 non-null    int64
 2   rating     737 non-null    int64
 3   timestamp  737 non-null    int64
dtypes: int64(4)
memory usage: 28.8 KB

In [ ]:
df_m = df_r.merge(df_movies, how='left', on='movie id')
df_m.head()

,user id,movie id,rating,timestamp,movie title,release date,video release date,IMDb URL,unknown,Action,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,405,56,4,885544911,Pulp Fiction (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Pulp%20Fictio...,0,0,...,0,0,0,0,0,0,0,0,0,0
1,405,592,1,885548670,True Crime (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?True%20Crime%...,0,0,...,0,0,0,0,1,0,0,1,0,0
2,405,1582,1,885548670,T-Men (1947),01-Jan-1947,NaN,http://us.imdb.com/M/title-exact?T-Men%20(1947),0,0,...,0,1,0,0,0,0,0,0,0,0
3,405,171,1,885549544,Delicatessen (1991),01-Jan-1991,NaN,http://us.imdb.com/M/title-exact?Delicatessen%...,0,0,...,0,0,0,0,0,0,1,0,0,0
4,405,580,1,885547447,"Englishman Who Went Up a Hill, But Came Down a...",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Englishman%20...,0,0,...,0,0,0,0,0,1,0,0,0,0

**● столбцы с общим количеством оценок от всех пользователей на фильм и суммарной оценкой от всех пользователей**

In [ ]:
df_count=df_ratings.groupby('user id').count().reset_index()
df_count=df_count[['user id','rating']]
df_count.rename(columns={'rating': 'count','user id':'movie id'}, inplace=True)
df_count.head(4)

   movie id  count
0         1    272
1         2     62
2         3     54
3         4     24

In [ ]:
df_sum=df_ratings.groupby('user id').sum().reset_index()
df_sum=df_sum[['user id','rating']]
df_sum.rename(columns={'rating': 'sum','user id':'movie id'}, inplace=True)
df_sum.head(4)

   movie id  sum
0         1  982
1         2  230
2         3  151
3         4  104

In [ ]:
df_resul = df_m.merge(df_sum,left_on="movie id",right_on="movie id",how="inner")
df_resul.head(3)

,user id,movie id,rating,timestamp,movie title,release date,video release date,IMDb URL,unknown,Action,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,sum
0,405,56,4,885544911,Pulp Fiction (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Pulp%20Fictio...,0,0,...,0,0,0,0,0,0,0,0,0,681
1,405,592,1,885548670,True Crime (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?True%20Crime%...,0,0,...,0,0,0,1,0,0,1,0,0,1373
2,405,171,1,885549544,Delicatessen (1991),01-Jan-1991,NaN,http://us.imdb.com/M/title-exact?Delicatessen%...,0,0,...,0,0,0,0,0,1,0,0,0,97

In [ ]:
df_resul = df_resul.merge(df_count,left_on="movie id",right_on="movie id",how="inner")
df_resul.head(3)

,user id,movie id,rating,timestamp,movie title,release date,video release date,IMDb URL,unknown,Action,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,sum,count
0,405,56,4,885544911,Pulp Fiction (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Pulp%20Fictio...,0,0,...,0,0,0,0,0,0,0,0,681,187
1,405,592,1,885548670,True Crime (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?True%20Crime%...,0,0,...,0,0,1,0,0,1,0,0,1373,360
2,405,171,1,885549544,Delicatessen (1991),01-Jan-1991,NaN,http://us.imdb.com/M/title-exact?Delicatessen%...,0,0,...,0,0,0,0,1,0,0,0,97,28

In [ ]:
df_resul['release date']=pd.to_datetime(df_resul['release date'],errors='coerce')

In [ ]:
df_resul['year']=df_resul['release date'].dt.year

In [ ]:
df_resul['month']=df_resul['release date'].dt.month
df_resul.head(3)

,user id,movie id,rating,timestamp,movie title,release date,video release date,IMDb URL,unknown,Action,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,sum,count,year,month
0,405,56,4,885544911,Pulp Fiction (1994),1994-01-01,NaN,http://us.imdb.com/M/title-exact?Pulp%20Fictio...,0,0,...,0,0,0,0,0,0,681,187,1994,1
1,405,592,1,885548670,True Crime (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?True%20Crime%...,0,0,...,1,0,0,1,0,0,1373,360,1995,1
2,405,171,1,885549544,Delicatessen (1991),1991-01-01,NaN,http://us.imdb.com/M/title-exact?Delicatessen%...,0,0,...,0,0,1,0,0,0,97,28,1991,1

Сформируйте X_train, X_test, y_train, y_test

In [ ]:
df_resul.columns

Index(['user id', 'movie id', 'rating', 'timestamp', 'movie title',
       'release date', 'video release date', 'IMDb URL', 'unknown', 'Action',
       ' Adventure', 'Animation', 'Children's', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western', 'sum',
       'count', 'year', 'month'],
      dtype='object')

In [ ]:
X, y = df_resul[['user id', 'movie id',  'timestamp',  'unknown', 'Action',
       ' Adventure', 'Animation', "Children's", 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western', 'sum',
       'count', 'year', 'month']], df_resul['rating']

In [ ]:
X

,user id,movie id,timestamp,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,sum,count,year,month
0,405,56,885544911,0,0,0,0,0,0,1,...,0,0,0,0,0,0,681,187,1994,1
1,405,592,885548670,0,0,0,0,0,0,0,...,1,0,0,1,0,0,1373,360,1995,1
2,405,171,885549544,0,0,0,0,0,1,0,...,0,0,1,0,0,0,97,28,1991,1
3,405,580,885547447,0,0,0,0,0,1,0,...,0,1,0,0,0,0,167,47,1995,1
4,405,387,885546680,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1022,304,1993,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,405,177,885547996,0,1,0,0,0,0,0,...,0,0,0,0,0,1,416,115,1966,1
482,405,513,885546112,0,0,0,0,0,0,0,...,1,0,0,1,0,0,96,22,1949,1
483,405,375,885546835,0,0,0,0,0,0,0,...,0,0,0,0,0,0,103,28,1995,1
484,405,445,885548435,0,0,0,0,0,0,0,...,0,0,0,0,0,0,268,135,1945,1
485,405,196,885546112,0,0,0,0,0,0,0,...,0,0,0,0,0,0,141,39,1989,1

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train.head()

,user id,movie id,timestamp,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,sum,count,year,month
40,405,719,885547447,0,0,0,0,0,1,0,...,0,0,0,0,1,0,208,67,1994,1
355,405,501,885548837,0,0,0,1,1,0,0,...,0,0,0,0,0,0,275,73,1941,1
53,405,62,885547996,0,1,1,0,0,0,0,...,0,0,1,0,0,0,766,232,1994,1
390,405,381,885547222,0,0,0,0,0,1,0,...,0,1,0,0,0,0,484,127,1994,1
460,405,466,885548633,0,0,0,0,0,0,0,...,0,0,0,1,0,0,350,101,1992,1

**Возьмите модель линейной регрессии (или любую другую для задачи регрессии)  и обучите ее на фильмах**

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

**Оцените качество модели на X_test, y_test при помощи метрик для задачи регрессии**

In [ ]:
mean_squared_error (y_test, model.predict(X_test))

1.7331301066765106

# **Вторая часть практики Python связана со Spark’ом**
**Загрузить данные в spark**

In [ ]:
!apt-get update

Get:1 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Hit:2 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:3 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:4 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:7 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:9 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main Sources [2,093 kB]
Ign:10 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:11 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1,581 B]
Hit:12 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:13 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main amd64 Packages [1,073 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:15 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ Packages [91.1 kB]
Get:16 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [912 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,938 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,311 kB]
Get:20 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,534 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3,369 kB]
Fetched 14.6 MB in 3s (5,297 kB/s)
Reading package lists... Done

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

In [ ]:
!wget -q https://downloads.apache.org/spark/spark-3.2.2/spark-3.2.2-bin-hadoop2.7.tgz

In [ ]:
!tar -xvf spark-3.2.2-bin-hadoop2.7.tgz

spark-3.2.2-bin-hadoop2.7/
spark-3.2.2-bin-hadoop2.7/RELEASE
spark-3.2.2-bin-hadoop2.7/LICENSE
spark-3.2.2-bin-hadoop2.7/NOTICE
spark-3.2.2-bin-hadoop2.7/README.md
spark-3.2.2-bin-hadoop2.7/jars/
spark-3.2.2-bin-hadoop2.7/jars/HikariCP-2.5.1.jar
spark-3.2.2-bin-hadoop2.7/jars/JLargeArrays-1.5.jar
spark-3.2.2-bin-hadoop2.7/jars/JTransforms-3.1.jar
spark-3.2.2-bin-hadoop2.7/jars/RoaringBitmap-0.9.0.jar
spark-3.2.2-bin-hadoop2.7/jars/ST4-4.0.4.jar
spark-3.2.2-bin-hadoop2.7/jars/activation-1.1.1.jar
spark-3.2.2-bin-hadoop2.7/jars/aircompressor-0.21.jar
spark-3.2.2-bin-hadoop2.7/jars/algebra_2.12-2.0.1.jar
spark-3.2.2-bin-hadoop2.7/jars/annotations-17.0.0.jar
spark-3.2.2-bin-hadoop2.7/jars/antlr-runtime-3.5.2.jar
spark-3.2.2-bin-hadoop2.7/jars/antlr4-runtime-4.8.jar
spark-3.2.2-bin-hadoop2.7/jars/aopalliance-1.0.jar
spark-3.2.2-bin-hadoop2.7/jars/aopalliance-repackaged-2.6.1.jar
spark-3.2.2-bin-hadoop2.7/jars/apacheds-i18n-2.0.0-M15.jar
spark-3.2.2-bin-hadoop2.7/jars/apacheds-kerberos-codec-2.0.0-M15.jar
spark-3.2.2-bin-hadoop2.7/jars/api-asn1-api-1.0.0-M20.jar
spark-3.2.2-bin-hadoop2.7/jars/api-util-1.0.0-M20.jar
spark-3.2.2-bin-hadoop2.7/jars/arpack-2.2.1.jar
spark-3.2.2-bin-hadoop2.7/jars/arpack_combined_all-0.1.jar
spark-3.2.2-bin-hadoop2.7/jars/arrow-format-2.0.0.jar
spark-3.2.2-bin-hadoop2.7/jars/arrow-memory-core-2.0.0.jar
spark-3.2.2-bin-hadoop2.7/jars/arrow-memory-netty-2.0.0.jar
spark-3.2.2-bin-hadoop2.7/jars/arrow-vector-2.0.0.jar
spark-3.2.2-bin-hadoop2.7/jars/audience-annotations-0.5.0.jar
spark-3.2.2-bin-hadoop2.7/jars/automaton-1.11-8.jar
spark-3.2.2-bin-hadoop2.7/jars/avro-1.10.2.jar
spark-3.2.2-bin-hadoop2.7/jars/avro-ipc-1.10.2.jar
spark-3.2.2-bin-hadoop2.7/jars/avro-mapred-1.10.2.jar
spark-3.2.2-bin-hadoop2.7/jars/blas-2.2.1.jar
spark-3.2.2-bin-hadoop2.7/jars/bonecp-0.8.0.RELEASE.jar
spark-3.2.2-bin-hadoop2.7/jars/breeze-macros_2.12-1.2.jar
spark-3.2.2-bin-hadoop2.7/jars/breeze_2.12-1.2.jar
spark-3.2.2-bin-hadoop2.7/jars/cats-kernel_2.12-2.1.1.jar
spark-3.2.2-bin-hadoop2.7/jars/chill-java-0.10.0.jar
spark-3.2.2-bin-hadoop2.7/jars/chill_2.12-0.10.0.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-beanutils-1.9.4.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-cli-1.2.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-codec-1.15.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-collections-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-compiler-3.0.16.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-compress-1.21.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-configuration-1.6.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-crypto-1.1.0.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-dbcp-1.4.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-digester-1.8.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-httpclient-3.1.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-io-2.4.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-lang-2.6.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-lang3-3.12.0.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-logging-1.1.3.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-math3-3.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-net-3.1.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-pool-1.5.4.jar
spark-3.2.2-bin-hadoop2.7/jars/commons-text-1.6.jar
spark-3.2.2-bin-hadoop2.7/jars/compress-lzf-1.0.3.jar
spark-3.2.2-bin-hadoop2.7/jars/core-1.1.2.jar
spark-3.2.2-bin-hadoop2.7/jars/curator-client-2.7.1.jar
spark-3.2.2-bin-hadoop2.7/jars/curator-framework-2.7.1.jar
spark-3.2.2-bin-hadoop2.7/jars/curator-recipes-2.7.1.jar
spark-3.2.2-bin-hadoop2.7/jars/datanucleus-api-jdo-4.2.4.jar
spark-3.2.2-bin-hadoop2.7/jars/datanucleus-core-4.1.17.jar
spark-3.2.2-bin-hadoop2.7/jars/datanucleus-rdbms-4.1.19.jar
spark-3.2.2-bin-hadoop2.7/jars/derby-10.14.2.0.jar
spark-3.2.2-bin-hadoop2.7/jars/dropwizard-metrics-hadoop-metrics2-reporter-0.1.2.jar
spark-3.2.2-bin-hadoop2.7/jars/flatbuffers-java-1.9.0.jar
spark-3.2.2-bin-hadoop2.7/jars/generex-1.0.2.jar
spark-3.2.2-bin-hadoop2.7/jars/gson-2.2.4.jar
spark-3.2.2-bin-hadoop2.7/jars/guava-14.0.1.jar
spark-3.2.2-bin-hadoop2.7/jars/guice-3.0.jar
spark-3.2.2-bin-hadoop2.7/jars/guice-servlet-3.0.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-annotations-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-auth-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-client-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-common-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-hdfs-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-mapreduce-client-app-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-mapreduce-client-common-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-mapreduce-client-core-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-mapreduce-client-jobclient-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-mapreduce-client-shuffle-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-yarn-api-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-yarn-client-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-yarn-common-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-yarn-server-common-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hadoop-yarn-server-web-proxy-2.7.4.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-beeline-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-cli-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-common-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-exec-2.3.9-core.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-jdbc-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-llap-common-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-metastore-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-serde-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-service-rpc-3.1.2.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-shims-0.23-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-shims-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-shims-common-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-shims-scheduler-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-storage-api-2.7.2.jar
spark-3.2.2-bin-hadoop2.7/jars/hive-vector-code-gen-2.3.9.jar
spark-3.2.2-bin-hadoop2.7/jars/hk2-api-2.6.1.jar
spark-3.2.2-bin-hadoop2.7/jars/hk2-locator-2.6.1.jar
spark-3.2.2-bin-hadoop2.7/jars/hk2-utils-2.6.1.jar
spark-3.2.2-bin-hadoop2.7/jars/htrace-core-3.1.0-incubating.jar
spark-3.2.2-bin-hadoop2.7/jars/httpclient-4.5.13.jar
spark-3.2.2-bin-hadoop2.7/jars/httpcore-4.4.14.jar
spark-3.2.2-bin-hadoop2.7/jars/istack-commons-runtime-3.0.8.jar
spark-3.2.2-bin-hadoop2.7/jars/ivy-2.5.0.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-annotations-2.12.3.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-core-2.12.3.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-core-asl-1.9.13.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-databind-2.12.3.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-dataformat-yaml-2.12.3.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-datatype-jsr310-2.11.2.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-jaxrs-1.9.13.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-mapper-asl-1.9.13.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-module-scala_2.12-2.12.3.jar
spark-3.2.2-bin-hadoop2.7/jars/jackson-xc-1.9.13.jar
spark-3.2.2-bin-hadoop2.7/jars/jakarta.annotation-api-1.3.5.jar
spark-3.2.2-bin-hadoop2.7/jars/jakarta.inject-2.6.1.jar
spark-3.2.2-bin-hadoop2.7/jars/jakarta.servlet-api-4.0.3.jar
spark-3.2.2-bin-hadoop2.7/jars/jakarta.validation-api-2.0.2.jar
spark-3.2.2-bin-hadoop2.7/jars/jakarta.ws.rs-api-2.1.6.jar
spark-3.2.2-bin-hadoop2.7/jars/jakarta.xml.bind-api-2.3.2.jar
spark-3.2.2-bin-hadoop2.7/jars/janino-3.0.16.jar
spark-3.2.2-bin-hadoop2.7/jars/javassist-3.25.0-GA.jar
spark-3.2.2-bin-hadoop2.7/jars/javax.inject-1.jar
spark-3.2.2-bin-hadoop2.7/jars/javax.jdo-3.2.0-m3.jar
spark-3.2.2-bin-hadoop2.7/jars/javolution-5.5.1.jar
spark-3.2.2-bin-hadoop2.7/jars/jaxb-api-2.2.11.jar
spark-3.2.2-bin-hadoop2.7/jars/jaxb-runtime-2.3.2.jar
spark-3.2.2-bin-hadoop2.7/jars/jcl-over-slf4j-1.7.30.jar
spark-3.2.2-bin-hadoop2.7/jars/jdo-api-3.0.1.jar
spark-3.2.2-bin-hadoop2.7/jars/jersey-client-2.34.jar
spark-3.2.2-bin-hadoop2.7/jars/jersey-common-2.34.jar
spark-3.2.2-bin-hadoop2.7/jars/jersey-container-servlet-2.34.jar
spark-3.2.2-bin-hadoop2.7/jars/jersey-container-servlet-core-2.34.jar
spark-3.2.2-bin-hadoop2.7/jars/jersey-hk2-2.34.jar
spark-3.2.2-bin-hadoop2.7/jars/jersey-server-2.34.jar
spark-3.2.2-bin-hadoop2.7/jars/jetty-6.1.26.jar
spark-3.2.2-bin-hadoop2.7/jars/jetty-sslengine-6.1.26.jar
spark-3.2.2-bin-hadoop2.7/jars/jetty-util-6.1.26.jar
spark-3.2.2-bin-hadoop2.7/jars/jline-2.14.6.jar
spark-3.2.2-bin-hadoop2.7/jars/joda-time-2.10.10.jar
spark-3.2.2-bin-hadoop2.7/jars/jodd-core-3.5.2.jar
spark-3.2.2-bin-hadoop2.7/jars/jpam-1.1.jar
spark-3.2.2-bin-hadoop2.7/jars/json-1.8.jar
spark-3.2.2-bin-hadoop2.7/jars/json4s-ast_2.12-3.7.0-M11.jar
spark-3.2.2-bin-hadoop2.7/jars/json4s-core_2.12-3.7.0-M11.jar
spark-3.2.2-bin-hadoop2.7/jars/json4s-jackson_2.12-3.7.0-M11.jar
spark-3.2.2-bin-hadoop2.7/jars/json4s-scalap_2.12-3.7.0-M11.jar
spark-3.2.2-bin-hadoop2.7/jars/jsp-api-2.1.jar
spark-3.2.2-bin-hadoop2.7/jars/jsr305-3.0.0.jar
spark-3.2.2-bin-hadoop2.7/jars/jta-1.1.jar
spark-3.2.2-bin-hadoop2.7/jars/jul-to-slf4j-1.7.30.jar
spark-3.2.2-bin-hadoop2.7/jars/kryo-shaded-4.0.2.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-client-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-admissionregistration-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-apiextensions-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-apps-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-autoscaling-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-batch-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-certificates-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-common-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-coordination-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-core-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-discovery-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-events-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-extensions-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-flowcontrol-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-metrics-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-networking-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-node-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-policy-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-rbac-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-scheduling-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/kubernetes-model-storageclass-5.4.1.jar
spark-3.2.2-bin-hadoop2.7/jars/lapack-2.2.1.jar
spark-3.2.2-bin-hadoop2.7/jars/leveldbjni-all-1.8.jar
spark-3.2.2-bin-hadoop2.7/jars/libfb303-0.9.3.jar
spark-3.2.2-bin-hadoop2.7/jars/libthrift-0.12.0.jar
spark-3.2.2-bin-hadoop2.7/jars/log4j-1.2.17.jar
spark-3.2.2-bin-hadoop2.7/jars/logging-interceptor-3.12.12.jar
spark-3.2.2-bin-hadoop2.7/jars/lz4-java-1.7.1.jar
spark-3.2.2-bin-hadoop2.7/jars/macro-compat_2.12-1.1.1.jar
spark-3.2.2-bin-hadoop2.7/jars/mesos-1.4.0-shaded-protobuf.jar
spark-3.2.2-bin-hadoop2.7/jars/metrics-core-4.2.0.jar
spark-3.2.2-bin-hadoop2.7/jars/metrics-graphite-4.2.0.jar
spark-3.2.2-bin-hadoop2.7/jars/metrics-jmx-4.2.0.jar
spark-3.2.2-bin-hadoop2.7/jars/metrics-json-4.2.0.jar
spark-3.2.2-bin-hadoop2.7/jars/metrics-jvm-4.2.0.jar
spark-3.2.2-bin-hadoop2.7/jars/minlog-1.3.0.jar
spark-3.2.2-bin-hadoop2.7/jars/netty-all-4.1.68.Final.jar
spark-3.2.2-bin-hadoop2.7/jars/objenesis-2.6.jar
spark-3.2.2-bin-hadoop2.7/jars/okhttp-3.12.12.jar
spark-3.2.2-bin-hadoop2.7/jars/okio-1.14.0.jar
spark-3.2.2-bin-hadoop2.7/jars/xz-1.8.jar
spark-3.2.2-bin-hadoop2.7/jars/opencsv-2.3.jar
spark-3.2.2-bin-hadoop2.7/jars/orc-core-1.6.14.jar
spark-3.2.2-bin-hadoop2.7/jars/orc-mapreduce-1.6.14.jar
spark-3.2.2-bin-hadoop2.7/jars/orc-shims-1.6.14.jar
spark-3.2.2-bin-hadoop2.7/jars/oro-2.0.8.jar
spark-3.2.2-bin-hadoop2.7/jars/osgi-resource-locator-1.0.3.jar
spark-3.2.2-bin-hadoop2.7/jars/paranamer-2.8.jar
spark-3.2.2-bin-hadoop2.7/jars/parquet-column-1.12.2.jar
spark-3.2.2-bin-hadoop2.7/jars/parquet-common-1.12.2.jar
spark-3.2.2-bin-hadoop2.7/jars/parquet-encoding-1.12.2.jar
spark-3.2.2-bin-hadoop2.7/jars/parquet-format-structures-1.12.2.jar
spark-3.2.2-bin-hadoop2.7/jars/parquet-hadoop-1.12.2.jar
spark-3.2.2-bin-hadoop2.7/jars/parquet-jackson-1.12.2.jar
spark-3.2.2-bin-hadoop2.7/jars/protobuf-java-2.5.0.jar
spark-3.2.2-bin-hadoop2.7/jars/py4j-0.10.9.5.jar
spark-3.2.2-bin-hadoop2.7/jars/pyrolite-4.30.jar
spark-3.2.2-bin-hadoop2.7/jars/rocksdbjni-6.20.3.jar
spark-3.2.2-bin-hadoop2.7/jars/scala-collection-compat_2.12-2.1.1.jar
spark-3.2.2-bin-hadoop2.7/jars/scala-compiler-2.12.15.jar
spark-3.2.2-bin-hadoop2.7/jars/scala-library-2.12.15.jar
spark-3.2.2-bin-hadoop2.7/jars/scala-parser-combinators_2.12-1.1.2.jar
spark-3.2.2-bin-hadoop2.7/jars/scala-reflect-2.12.15.jar
spark-3.2.2-bin-hadoop2.7/jars/scala-xml_2.12-1.2.0.jar
spark-3.2.2-bin-hadoop2.7/jars/shapeless_2.12-2.3.3.jar
spark-3.2.2-bin-hadoop2.7/jars/shims-0.9.0.jar
spark-3.2.2-bin-hadoop2.7/jars/slf4j-api-1.7.30.jar
spark-3.2.2-bin-hadoop2.7/jars/slf4j-log4j12-1.7.30.jar
spark-3.2.2-bin-hadoop2.7/jars/snakeyaml-1.27.jar
spark-3.2.2-bin-hadoop2.7/jars/snappy-java-1.1.8.4.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-catalyst_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-core_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-graphx_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-hive-thriftserver_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-hive_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-kubernetes_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-kvstore_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-launcher_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-mesos_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-mllib-local_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-mllib_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-network-common_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-network-shuffle_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-repl_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-sketch_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-sql_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-streaming_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-tags_2.12-3.2.2-tests.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-tags_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-unsafe_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spark-yarn_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/jars/spire-macros_2.12-0.17.0.jar
spark-3.2.2-bin-hadoop2.7/jars/spire-platform_2.12-0.17.0.jar
spark-3.2.2-bin-hadoop2.7/jars/spire-util_2.12-0.17.0.jar
spark-3.2.2-bin-hadoop2.7/jars/spire_2.12-0.17.0.jar
spark-3.2.2-bin-hadoop2.7/jars/stax-api-1.0.1.jar
spark-3.2.2-bin-hadoop2.7/jars/stream-2.9.6.jar
spark-3.2.2-bin-hadoop2.7/jars/super-csv-2.2.0.jar
spark-3.2.2-bin-hadoop2.7/jars/threeten-extra-1.5.0.jar
spark-3.2.2-bin-hadoop2.7/jars/tink-1.6.0.jar
spark-3.2.2-bin-hadoop2.7/jars/transaction-api-1.1.jar
spark-3.2.2-bin-hadoop2.7/jars/univocity-parsers-2.9.1.jar
spark-3.2.2-bin-hadoop2.7/jars/velocity-1.5.jar
spark-3.2.2-bin-hadoop2.7/jars/xbean-asm9-shaded-4.20.jar
spark-3.2.2-bin-hadoop2.7/jars/xercesImpl-2.12.2.jar
spark-3.2.2-bin-hadoop2.7/jars/xml-apis-1.4.01.jar
spark-3.2.2-bin-hadoop2.7/jars/xmlenc-0.52.jar
spark-3.2.2-bin-hadoop2.7/jars/zjsonpatch-0.3.0.jar
spark-3.2.2-bin-hadoop2.7/jars/zookeeper-3.6.2.jar
spark-3.2.2-bin-hadoop2.7/jars/zookeeper-jute-3.6.2.jar
spark-3.2.2-bin-hadoop2.7/jars/zstd-jni-1.5.0-4.jar
spark-3.2.2-bin-hadoop2.7/yarn/
spark-3.2.2-bin-hadoop2.7/yarn/spark-3.2.2-yarn-shuffle.jar
spark-3.2.2-bin-hadoop2.7/kubernetes/
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/Dockerfile
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/entrypoint.sh
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/decom.sh
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/bindings/
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/bindings/R/
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/bindings/R/Dockerfile
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/bindings/python/
spark-3.2.2-bin-hadoop2.7/kubernetes/dockerfiles/spark/bindings/python/Dockerfile
spark-3.2.2-bin-hadoop2.7/kubernetes/tests/
spark-3.2.2-bin-hadoop2.7/kubernetes/tests/autoscale.py
spark-3.2.2-bin-hadoop2.7/kubernetes/tests/decommissioning.py
spark-3.2.2-bin-hadoop2.7/kubernetes/tests/decommissioning_cleanup.py
spark-3.2.2-bin-hadoop2.7/kubernetes/tests/py_container_checks.py
spark-3.2.2-bin-hadoop2.7/kubernetes/tests/pyfiles.py
spark-3.2.2-bin-hadoop2.7/kubernetes/tests/python_executable_check.py
spark-3.2.2-bin-hadoop2.7/kubernetes/tests/worker_memory_check.py
spark-3.2.2-bin-hadoop2.7/examples/
spark-3.2.2-bin-hadoop2.7/examples/jars/
spark-3.2.2-bin-hadoop2.7/examples/jars/scopt_2.12-3.7.1.jar
spark-3.2.2-bin-hadoop2.7/examples/jars/spark-examples_2.12-3.2.2.jar
spark-3.2.2-bin-hadoop2.7/examples/src/
spark-3.2.2-bin-hadoop2.7/examples/src/main/
spark-3.2.2-bin-hadoop2.7/examples/src/main/scripts/
spark-3.2.2-bin-hadoop2.7/examples/src/main/scripts/getGpusResources.sh
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.2.2-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java

In [ ]:
!pip install -q findspark

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.2-bin-hadoop2.7"

In [ ]:
import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()
sc = spark.sparkContext

In [ ]:
df_data = spark.read.csv('u.data.csv',sep='\t' , inferSchema=True, header=False)

In [ ]:
df_data.describe().show()

+-------+------------------+------------------+------------------+-----------------+
|summary|               _c0|               _c1|               _c2|              _c3|
+-------+------------------+------------------+------------------+-----------------+
|  count|            100000|            100000|            100000|           100000|
|   mean|         462.48475|         425.53013|           3.52986|8.8352885148862E8|
| stddev|266.61442012750905|330.79835632558473|1.1256735991443214|5343856.189502848|
|    min|                 1|                 1|                 1|        874724710|
|    max|               943|              1682|                 5|        893286638|
+-------+------------------+------------------+------------------+-----------------+

In [ ]:
df_data =df_data.withColumnRenamed('_c0','User_Id').withColumnRenamed('_c1','Movie_Id').withColumnRenamed('_c2','Rating').withColumnRenamed('_c3','Date')
df_data.show(5)

+-------+--------+------+---------+
|User_Id|Movie_Id|Rating|     Date|
+-------+--------+------+---------+
|    196|     242|     3|881250949|
|    186|     302|     3|891717742|
|     22|     377|     1|878887116|
|    244|      51|     2|880606923|
|    166|     346|     1|886397596|
+-------+--------+------+---------+
only showing top 5 rows

In [ ]:
df_item = spark.read.csv('u.item.csv',sep='|' , inferSchema=True, header=False)

In [ ]:
df_item.describe().show()

+-------+------------------+--------------------+-----------+----+--------------------+--------------------+-------------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+-------------------+-------------------+-------------------+------------------+-------------------+-------------------+
|summary|               _c0|                 _c1|        _c2| _c3|                 _c4|                 _c5|                _c6|               _c7|                _c8|                _c9|               _c10|               _c11|                _c12|               _c13|                _c14|                _c15|                _c16|               _c17|               _c18|               _c19|               _c20|              _c21|               _c22|               _c23|
+-------+------------------+--------------------+-----------+----+--------------------+--------------------+-------------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+-------------------+-------------------+-------------------+------------------+-------------------+-------------------+
|  count|              1682|                1682|       1681|   0|                1679|                1682|               1682|              1682|               1682|               1682|               1682|               1682|                1682|               1682|                1682|                1682|                1682|               1682|               1682|               1682|               1682|              1682|               1682|               1682|
|   mean|             841.5|                null|       null|null|                null|0.001189060642092...| 0.1492271105826397|0.0802615933412604|0.02497027348394768|0.07253269916765755|0.30023781212841855|0.06480380499405469|0.029726516052318668|0.43103448275862066|0.013079667063020214|0.014268727705112961|0.054696789536266346|0.03329369797859691|0.03626634958382877|0.14684898929845422|0.06004756242568371|0.1492271105826397|0.04221165279429251|0.01605231866825208|
| stddev|485.69589250888254|                null|       null|null|                null|0.034472500474212284|0.35641816109515484|0.2717785571305444|0.15608088423430846|0.25944503383362605| 0.4584976014014335| 0.2462525621467922| 0.16988233706244027| 0.4953681954046321| 0.11364976236574524| 0.11863177582846385|  0.2274550708557175|0.17945577207322622| 0.1870077359968219|0.35406057857880563| 0.2376455954301871|0.3564181610951548|0.20113149982303108| 0.1257141110346824|
|    min|                 1|'Til There Was Yo...|01-Aug-1997|null|http://us.imdb.co...|                   0|                  0|                 0|                  0|                  0|                  0|                  0|                   0|                  0|                   0|                   0|                   0|                  0|                  0|                  0|                  0|                 0|                  0|                  0|
|    max|              1682|� k�ldum klaka (C...| 4-Feb-1971|null|http://us.imdb.co...|                   1|                  1|                 1|                  1|                  1|                  1|                  1|                   1|                  1|                   1|                   1|                   1|                  1|                  1|                  1|                  1|                 1|                  1|                  1|
+-------+------------------+--------------------+-----------+----+--------------------+--------------------+-------------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+-------------------+-------------------+-------------------+-------------------+------------------+-------------------+-------------------+

In [ ]:
df_item =df_item.withColumnRenamed('_c0','Movie_id1').withColumnRenamed('_c1','Title').withColumnRenamed('_c2','Release_date')\
.withColumnRenamed('_c3','Video_release_date').withColumnRenamed('_c4','IMDb_URL').withColumnRenamed('_c5','unknown')\
.withColumnRenamed('_c6','Action').withColumnRenamed('_c7','Adventure').withColumnRenamed('_c8','Animation')\
.withColumnRenamed('_c9','Children').withColumnRenamed('_c10','Comedy').withColumnRenamed('_c11','Crime')\
.withColumnRenamed('_c12','Documentary').withColumnRenamed('_c13','Drama').withColumnRenamed('_c14','Fantasy')\
.withColumnRenamed('_c15','Film_Noir').withColumnRenamed('_c16','Horror').withColumnRenamed('_c17','Musical')\
.withColumnRenamed('_c18','Mystery').withColumnRenamed('_c19','Romance').withColumnRenamed('_c20','Sci_Fi')\
.withColumnRenamed('_c21','Thriller').withColumnRenamed('_c22','War').withColumnRenamed('_c23','Western')
df_item.show()

+---------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|Movie_id1|               Title|Release_date|Video_release_date|            IMDb_URL|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+---------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|        1|    Toy Story (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        1|       1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|        2|    GoldenEye (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        1|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|        3|   Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|        4|   Get Shorty (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        0|        0|       0|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|        5|      Copycat (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|        6|Shanghai Triad (Y...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|        7|Twelve Monkeys (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     1|       0|  0|      0|
|        8|         Babe (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       1|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|        9|Dead Man Walking ...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       10|  Richard III (1995)| 22-Jan-1996|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  1|      0|
|       11|Seven (Se7en) (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       12|Usual Suspects, T...| 14-Aug-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       13|Mighty Aphrodite ...| 30-Oct-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       14|  Postino, Il (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
|       15|Mr. Holland's Opu...| 29-Jan-1996|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       16|French Twist (Gaz...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
|       17|From Dusk Till Da...| 05-Feb-1996|              null|http://us.imdb.co...|      0|     1|        0|        0|       0|     1|    1|          0|    0|      0|        0|     1|      0|      0|      0|     0|       1|  0|      0|
|       18|White Balloon, Th...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       19|Antonia's Line (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       20|Angels and Insect...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
+---------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 20 rows

**Средствами спарка вывести среднюю оценку для каждого фильма**

In [ ]:
from pyspark.sql.functions import *

In [ ]:
df_data =df_data.alias('data')
df_item = df_item.alias('item')
PYratings = df_data.join(df_item, df_data.Movie_Id == df_item.Movie_id1, 'left')
PYratings.show(5)

+-------+--------+------+---------+---------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|User_Id|Movie_Id|Rating|     Date|Movie_id1|               Title|Release_date|Video_release_date|            IMDb_URL|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+-------+--------+------+---------+---------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|    196|     242|     3|881250949|      242|        Kolya (1996)| 24-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    186|     302|     3|891717742|      302|L.A. Confidential...| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|
|     22|     377|     1|878887116|      377| Heavyweights (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|       1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    244|      51|     2|880606923|       51|Legends of the Fa...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|
|    166|     346|     1|886397596|      346| Jackie Brown (1997)| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|        0|       0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
+-------+--------+------+---------+---------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [ ]:
PYratings = PYratings.drop('Movie_Id1', 'Video_release_date', 'IMDb_URL', 'Date')
PYratings.show(5)

+-------+--------+------+--------------------+------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|User_Id|Movie_Id|Rating|               Title|Release_date|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+-------+--------+------+--------------------+------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|    196|     242|     3|        Kolya (1996)| 24-Jan-1997|      0|     0|        0|        0|       0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    186|     302|     3|L.A. Confidential...| 01-Jan-1997|      0|     0|        0|        0|       0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|
|     22|     377|     1| Heavyweights (1994)| 01-Jan-1994|      0|     0|        0|        0|       1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    244|      51|     2|Legends of the Fa...| 01-Jan-1994|      0|     0|        0|        0|       0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|
|    166|     346|     1| Jackie Brown (1997)| 01-Jan-1997|      0|     0|        0|        0|       0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
+-------+--------+------+--------------------+------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [ ]:
PYratings.groupBy('Movie_Id', 'Title').avg('Rating').show(5)

+--------+--------------------+------------------+
|Movie_Id|               Title|       avg(Rating)|
+--------+--------------------+------------------+
|     171| Delicatessen (1991)| 3.876923076923077|
|     279|Once Upon a Time....|3.2857142857142856|
|     873|Picture Perfect (...| 2.962962962962963|
|     660|Fried Green Tomat...| 3.764705882352941|
|     708|Sex, Lies, and Vi...|3.4752475247524752|
+--------+--------------------+------------------+
only showing top 5 rows

**Посчитайте средствами спарка среднюю оценку для каждого жанра**

In [ ]:
test = PYratings.withColumn('unknown', when(col('unknown').isin('1'), "unknown")\
                            .otherwise(when(col('unknown').isin('0'), "")
                            .otherwise(PYratings.unknown)))
test = test.withColumn('Action', when(col('Action').isin('1'), "Action")\
                            .otherwise(when(col('Action').isin('0'), "")
                            .otherwise(test.Action)))
test = test.withColumn('Adventure', when(col('Adventure').isin('1'), "Adventure")\
                            .otherwise(when(col('Adventure').isin('0'), "")
                            .otherwise(test.Adventure)))
test = test.withColumn('Animation', when(col('Animation').isin('1'), "Animation")\
                            .otherwise(when(col('Animation').isin('0'), "")
                            .otherwise(test.Animation)))
test = test.withColumn('Children', when(col('Children').isin('1'), "Children")\
                            .otherwise(when(col('Children').isin('0'), "")
                            .otherwise(test.Children)))
test = test.withColumn('Comedy', when(col('Comedy').isin('1'), "Comedy")\
                            .otherwise(when(col('Comedy').isin('0'), "")
                            .otherwise(test.Comedy)))
test = test.withColumn('Crime', when(col('Crime').isin('1'), "Crime")\
                            .otherwise(when(col('Crime').isin('0'), "")
                            .otherwise(test.Crime)))
test = test.withColumn('Documentary', when(col('Documentary').isin('1'), "Documentary")\
                            .otherwise(when(col('Documentary').isin('0'), "")
                            .otherwise(test.Documentary)))
test = test.withColumn('Drama', when(col('Drama').isin('1'), "Drama")\
                            .otherwise(when(col('Drama').isin('0'), "")
                            .otherwise(test.Drama)))
test = test.withColumn('Fantasy', when(col('Fantasy').isin('1'), "Fantasy")\
                            .otherwise(when(col('Fantasy').isin('0'), "")
                            .otherwise(test.Fantasy)))
test = test.withColumn('Film_Noir', when(col('Film_Noir').isin('1'), "Film_Noir")\
                            .otherwise(when(col('Film_Noir').isin('0'), "")
                            .otherwise(test.Film_Noir)))
test = test.withColumn('Horror', when(col('Horror').isin('1'), "Horror")\
                            .otherwise(when(col('Horror').isin('0'), "")
                            .otherwise(test.Horror)))
test = test.withColumn('Musical', when(col('Musical').isin('1'), "Musical")\
                            .otherwise(when(col('Musical').isin('0'), "")
                            .otherwise(test.Musical)))
test = test.withColumn('Mystery', when(col('Mystery').isin('1'), "Mystery")\
                            .otherwise(when(col('Mystery').isin('0'), "")
                            .otherwise(test.Mystery)))
test = test.withColumn('Romance', when(col('Romance').isin('1'), "Romance")\
                            .otherwise(when(col('Romance').isin('0'), "")
                            .otherwise(test.Romance)))
test = test.withColumn('Sci_Fi', when(col('Sci_Fi').isin('1'), "Sci_Fi")\
                            .otherwise(when(col('Sci_Fi').isin('0'), "")
                            .otherwise(test.Sci_Fi)))
test = test.withColumn('Thriller', when(col('Thriller').isin('1'), "Thriller")\
                            .otherwise(when(col('Thriller').isin('0'), "")
                            .otherwise(test.Thriller)))
test = test.withColumn('War', when(col('War').isin('1'), "War")\
                            .otherwise(when(col('War').isin('0'), "")
                            .otherwise(test.War)))
test = test.withColumn('Western', when(col('Western').isin('1'), "Western")\
                            .otherwise(when(col('Western').isin('0'), "")
                            .otherwise(test.Western)))

In [ ]:
test.show()

+-------+--------+------+--------------------+------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|User_Id|Movie_Id|Rating|               Title|Release_date|unknown|Action|Adventure|Animation|Children|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+-------+--------+------+--------------------+------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|    196|     242|     3|        Kolya (1996)| 24-Jan-1997|       |      |         |         |        |Comedy|     |           |     |       |         |      |       |       |       |      |        |   |       |
|    186|     302|     3|L.A. Confidential...| 01-Jan-1997|       |      |         |         |        |      |Crime|           |     |       |Film_Noir|      |       |Mystery|       |      |Thriller|   |       |
|     22|     377|     1| Heavyweights (1994)| 01-Jan-1994|       |      |         |         |Children|Comedy|     |           |     |       |         |      |       |       |       |      |        |   |       |
|    244|      51|     2|Legends of the Fa...| 01-Jan-1994|       |      |         |         |        |      |     |           |Drama|       |         |      |       |       |Romance|      |        |War|Western|
|    166|     346|     1| Jackie Brown (1997)| 01-Jan-1997|       |      |         |         |        |      |Crime|           |Drama|       |         |      |       |       |       |      |        |   |       |
|    298|     474|     4|Dr. Strangelove o...| 01-Jan-1963|       |      |         |         |        |      |     |           |     |       |         |      |       |       |       |Sci_Fi|        |War|       |
|    115|     265|     2|Hunt for Red Octo...| 01-Jan-1990|       |Action|         |         |        |      |     |           |     |       |         |      |       |       |       |      |Thriller|   |       |
|    253|     465|     5|Jungle Book, The ...| 01-Jan-1994|       |      |Adventure|         |Children|      |     |           |     |       |         |      |       |       |Romance|      |        |   |       |
|    305|     451|     3|       Grease (1978)| 01-Jan-1978|       |      |         |         |        |Comedy|     |           |     |       |         |      |Musical|       |Romance|      |        |   |       |
|      6|      86|     3|Remains of the Da...| 01-Jan-1993|       |      |         |         |        |      |     |           |Drama|       |         |      |       |       |       |      |        |   |       |
|     62|     257|     2| Men in Black (1997)| 04-Jul-1997|       |Action|Adventure|         |        |Comedy|     |           |     |       |         |      |       |       |       |Sci_Fi|        |   |       |
|    286|    1014|     5|Romy and Michele'...| 25-Apr-1997|       |      |         |         |        |Comedy|     |           |     |       |         |      |       |       |       |      |        |   |       |
|    200|     222|     5|Star Trek: First ...| 22-Nov-1996|       |Action|Adventure|         |        |      |     |           |     |       |         |      |       |       |       |Sci_Fi|        |   |       |
|    210|      40|     3|To Wong Foo, Than...| 01-Jan-1995|       |      |         |         |        |Comedy|     |           |     |       |         |      |       |       |       |      |        |   |       |
|    224|      29|     3|Batman Forever (1...| 01-Jan-1995|       |Action|Adventure|         |        |Comedy|Crime|           |     |       |         |      |       |       |       |      |        |   |       |
|    303|     785|     3|     Only You (1994)| 01-Jan-1994|       |      |         |         |        |Comedy|     |           |     |       |         |      |       |       |Romance|      |        |   |       |
|    122|     387|     5|Age of Innocence,...| 01-Jan-1993|       |      |         |         |        |      |     |           |Drama|       |         |      |       |       |       |      |        |   |       |
|    194|     274|     2|      Sabrina (1995)| 01-Jan-1995|       |      |         |         |        |Comedy|     |           |     |       |         |      |       |       |Romance|      |        |   |       |
|    291|    1042|     4|   Just Cause (1995)| 01-Jan-1995|       |      |         |         |        |      |     |           |     |       |         |      |       |Mystery|       |      |Thriller|   |       |
|    234|    1184|     2|Endless Summer 2,...| 01-Jan-1994|       |      |         |         |        |      |     |Documentary|     |       |         |      |       |       |       |      |        |   |       |
+-------+--------+------+--------------------+------------+-------+------+---------+---------+--------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 20 rows

In [ ]:
test1 = test.select(concat_ws('', test.unknown, test.Action, test.Adventure, test.Animation, test.Children, test.Comedy, test.Crime,\
                              test.Documentary, test.Drama, test.Fantasy, test.Film_Noir, test.Horror, test.Musical, test.Mystery,\
                              test.Romance, test.Sci_Fi, test.Thriller, test.War, test.Western).alias('Genre'), test.Rating)

In [ ]:
test1 = test1.groupBy('Genre').avg('Rating')

In [ ]:
test1.show()

+--------------------+------------------+
|               Genre|       avg(Rating)|
+--------------------+------------------+
|AdventureAnimatio...|2.7209302325581395|
|AdventureComedyDrama| 3.881057268722467|
|     AnimationSci_Fi|3.6538461538461537|
|      Sci_FiThriller|2.7041884816753927|
|ActionAdventureCo...|        2.67578125|
|ActionAdventureCh...|               1.8|
|               Crime| 3.003086419753086|
|AnimationChildren...|3.8127853881278537|
|AdventureDramaWes...|        3.79296875|
|DramaRomanceWarWe...|  3.45679012345679|
|             Romance| 3.300395256916996|
|      ComedyDramaWar| 3.180327868852459|
|            Thriller|3.3107861060329067|
|    ComedyRomanceWar| 3.853582554517134|
|ActionAdventureCo...| 2.761904761904762|
|ActionAdventureCo...| 3.303370786516854|
|ActionHorrorSci_F...|3.7263427109974425|
|ActionAdventureSc...|3.4273458445040212|
|        DramaMusical| 3.110275689223058|
|    CrimeDramaSci_Fi| 3.513333333333333|
+--------------------+------------------+
only showing top 20 rows

**В спарке получить 2 датафрейма с 5-ю самыми популярными и самыми непопулярными фильмами (по оценке)**

In [ ]:
a = PYratings.groupBy('Movie_Id', 'Title').avg('Rating')

In [ ]:
a.orderBy('avg(Rating)', ascending=False).show(5)

+--------+--------------------+-----------+
|Movie_Id|               Title|avg(Rating)|
+--------+--------------------+-----------+
|    1653|Entertaining Ange...|        5.0|
|    1293|     Star Kid (1997)|        5.0|
|    1599|Someone Else's Am...|        5.0|
|    1189|  Prefontaine (1997)|        5.0|
|    1536|Aiqing wansui (1994)|        5.0|
+--------+--------------------+-----------+
only showing top 5 rows

In [ ]:
a.orderBy('avg(Rating)', ascending=True).show(5)

+--------+--------------------+-----------+
|Movie_Id|               Title|avg(Rating)|
+--------+--------------------+-----------+
|     314|3 Ninjas: High No...|        1.0|
|    1618|King of New York ...|        1.0|
|    1341|     Hedd Wyn (1992)|        1.0|
|    1572|Wend Kuuni (God's...|        1.0|
|    1494|   Mostro, Il (1994)|        1.0|
+--------+--------------------+-----------+
only showing top 5 rows